title: Wordpress Tutorial
author: Amir Mahmoud Ebrahimi
email: amirebrahimi5@gmail.com
description: TradeMarks 2020
twitter_username: AmirMahmoudEbra
github_username: amebrahimi

markdown: kramdown
theme: jekyll-theme-hacker
